export const XPATHS = {
  base: {
    cookieAcceptLink: "//a[normalize-space(text())='PARAM']",
    geoDialogBtn: "//a[@aria-label='PARAM']"
  },
  home: {
    navToggle: "//button[contains(@class,'PARAM')]",
    primaryNavTopLevelLinks: "//*[contains(@class,\"primary-nav\")]//a[@href=\"#\"]",
    primaryNavLink: "//*[contains(@class,'primary-nav')]//a[normalize-space(text())='PARAM']",
    subMenuLink: "//*[contains(@class,'primary-nav__sub')]//a[normalize-space(text())='PARAM']",
    searchBtn: "//button[@aria-label='PARAM']",
    linkByHref: "//a[contains(@href,'PARAM')]",
    inputByPlaceholder: "//input[@placeholder='PARAM']",
    checkboxByType: "//input[@type='PARAM']",
    checkboxFirst: "//input[@type=\"checkbox\"]",
    hoverMenuTriggerByText: "//a[not(ancestor::footer) and normalize-space(.)='PARAM']",
    openSearchFallback: "//button[contains(@class,\"search\")] | //button[svg] | //a[@aria-label=\"Search the site\"]",
    searchInputFallback: "//input[@type=\"search\"] | //input[@type=\"text\"][contains(@class,\"search\")] | //input[@placeholder=\"Search\"]",
    logoToHome: "//header//a[./img] | //a[contains(@class,\"site-header__logo\")] | //a[contains(@class,\"primary-nav__logo\")]",
    featuredStoriesCards: "//h2[contains(normalize-space(.),\"Featured Stories\")]/ancestor::*[self::section or self::div][.//article][1]//article",
    featuredStoriesImages: "//h2[contains(normalize-space(.),\"Featured Stories\")]/ancestor::*[self::section or self::div][.//article][1]//article//img",
    featuredStoriesDates: "//h2[contains(normalize-space(.),\"Featured Stories\")]/ancestor::*[self::section or self::div][.//article][1]//article//time",
    featuredStoriesLinks: "//h2[contains(normalize-space(.),\"Featured Stories\")]/ancestor::*[self::section or self::div][.//article][1]//article//a[contains(@href,\"/insights/article/\")]",
    privateWealthLearnMoreLink: "//a[contains(@href,\"/pws\") and normalize-space(.)=\"Learn More\"]",
    searchResultsItems: "//*[contains(@class,'result') or contains(@class,'search-result') or contains(@class,'Result')]//a | //article | //li[contains(@class,'result')]",
    submitButton: "//button[contains(@class,\"submit\") or normalize-space(text())=\"Submit\"] | //input[@type=\"submit\"]",
    countryCombobox: "//*[contains(@name,\"country\")][@type=\"text\"]/ancestor::div[@role=\"combobox\"][1]",
    countryOptionByLabel: "//span[contains(@class,\"bx-dropdown-option__label\") and normalize-space(text())=\"PARAM\"]",
    footerRoot: "//footer",
    footerBrandingText: "//footer//*[contains(normalize-space(text()),\"Blackstone\") or contains(normalize-space(text()),\"blackstone\")]",
    footerLogoImage: "//footer//img[contains(translate(@alt,\"abcdefghijklmnopqrstuvwxyz\",\"ABCDEFGHIJKLMNOPQRSTUVWXYZ\"),\"BLACKSTONE\") or contains(@src,\"logo\") or contains(@src,\"blackstone\")]",
    footerLinksNavigable: "//footer//a[@href and normalize-space(text())!=\"\" and not(@aria-label=\"Blackstone home\")]",
    footerAnyHref: "//footer//a[@href]",
    footerLinkByText: "//footer//a[normalize-space(text())='PARAM']",
    footerFirmLink: "//footer//a[normalize-space(text())='The Firm']",
    bodyElement: "//body",
    headerOrSubheading: "//h1 | //h2",
    ourPeopleLink: "//a[not(ancestor::footer) and normalize-space(.)='Our People']",
    realEstateLink: "//a[not(ancestor::footer) and normalize-space(.)='Real Estate']",
    emailFieldRequired: "//input[@placeholder=\"Email Address *\"]",
    firstNameField: "//input[@placeholder=\"First Name *\"]",
    lastNameField: "//input[@placeholder=\"Last Name *\"]"
  }
} as const;
